### PR TITLE
Create flathub.json and update to v1.1.1

### PR DESCRIPTION
**Pull request by serebit**
Automatically merge flathubbot PRs

### CODE REVIEW

**Comment by cassidyjames** [comment]
@serebit go ahead and have the bot retry by commenting:

```
bot, build
```

https://docs.flathub.org/docs/for-app-authors/maintenance#test-builds-and-pull-requests

Edit: ah, never mind, it looks like I kicked it off. 😁

**Comment by serebit** [comment]
Well that doesn't seem right...

**Comment by serebit** [comment]
@cassidyjames Checked back, and though I had to wait 10-20 seconds per dropdown for things to load, I did eventually manage to get to the build output. Sorry for the false report. I think some loading indicators in buildbot would be helpful if the loading speed can't be improved.

**Comment by cassidyjames** [comment]
@serebit no worries; I think buildbot is just slooooow due to [rebuilding every app in the store with the new AppStream library](https://docs.flathub.org/blog/improved-build-validation). It's usually a lot more performant!

In case you missed it, it looks like these are the errors:

```json
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "finish-args-x11-without-ipc"
    ],
    "appstream": [
        "W: dev.serebit.Waycheck:44: relation-display-length-value-invalid xsmall",
        "E: dev.serebit.Waycheck:55: screenshot-image-source-missing",
        "E: dev.serebit.Waycheck:59: screenshot-image-source-missing"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by serebit** [comment]
bot, build

**Pull request merged**
